import React, { useMemo, useState } from 'react';
import { StyleSheet, View, Text, ScrollView, Share, Linking, Alert } from 'react-native';
import Animated, { FadeInDown } from 'react-native-reanimated';
import Screen from '../components/Screen';
import Button from '../components/Button';
import Segmented from '../components/Segmented';
import { code as ink, spacing, typography } from '../theme/tokens';

// Pencil-and-highlighter syntax hues on the clean proof. A line-local regex
// pass is enough for the JSX this app generates; it never needs to be a parser.
const TOKEN = /(\/\/.*$)|('(?:[^'\\]|\\.)*'|"(?:[^"\\]|\\.)*"|`(?:[^`\\]|\\.)*`)|(<\/?[A-Z][A-Za-z]*)|\b(import|from|export|default|const|let|var|return|function|class|extends|new)\b|\b(\d+(?:\.\d+)?)\b/g;
const KINDS = [null, 'comment', 'string', 'tag', 'keyword', 'number'];

function tokenize(line) {
  const out = [];
  let last = 0;
  let m;
  TOKEN.lastIndex = 0;
  while ((m = TOKEN.exec(line)) !== null) {
    if (m.index > last) out.push({ text: line.slice(last, m.index) });
    const kind = KINDS[m.slice(1).findIndex((g) => g !== undefined) + 1];
    out.push({ text: m[0], kind });
    last = m.index + m[0].length;
    if (m[0].length === 0) TOKEN.lastIndex++;
  }
  if (last < line.length) out.push({ text: line.slice(last) });
  return out;
}

// Renders the code string passed in via route.params - already generated
// locally in reviewDetections.js, or loaded from the saved sketch in
// sketchProfile.js. Toggles to the Enhance step's output when available.
export default function DisplaySourceCode({ route }) {
  const { sname, code, enhancedCode } = route.params;
  const [showEnhanced, setShowEnhanced] = useState(!!enhancedCode);
  const displayedCode = showEnhanced && enhancedCode ? enhancedCode : code;
  const lines = useMemo(() => String(displayedCode || '').split('\n'), [displayedCode]);
  const gutterWidth = String(lines.length).length * 9 + 16;

  const shareEvent = async () => {
    try {
      await Share.share({
        message: displayedCode,
        title: `Layout: ${sname.replace(/_/g, ' ')} - code generated by autoreact`,
      });
    } catch (error) {
      console.error(error);
    }
  };

  // Snack takes the file straight from the URL, so the generated component
  // runs on the phone in seconds. Generated code only imports react-native.
  const runInSnack = async () => {
    const name = sname.replace(/_/g, ' ');
    const url = `https://snack.expo.dev/?name=${encodeURIComponent(name)}&platform=android&code=${encodeURIComponent(displayedCode)}`;
    try {
      await Linking.openURL(url);
    } catch {
      Alert.alert("Couldn't open Snack", 'Use Copy or share instead and paste the code into snack.expo.dev.');
    }
  };

  return (
    <Screen padded={false} center={false} style={styles.screen}>
      <View style={styles.head}>
        {enhancedCode ? (
          <Segmented
            tone="ink"
            value={showEnhanced}
            onChange={setShowEnhanced}
            options={[{ label: 'Offline', value: false }, { label: 'Enhanced', value: true }]}
          />
        ) : null}
        <Text style={styles.slug}>{lines.length} lines · {sname.replace(/_/g, ' ')}</Text>
      </View>

      <ScrollView style={styles.vertical} contentContainerStyle={styles.verticalContent}>
        <ScrollView horizontal showsHorizontalScrollIndicator contentContainerStyle={styles.horizontalContent}>
          <View>
            {lines.map((line, i) => (
              <Animated.View key={i} entering={FadeInDown.delay(Math.min(i, 24) * 22).duration(220)} style={styles.line}>
                <Text style={[styles.gutter, { width: gutterWidth }]}>{i + 1}</Text>
                <Text style={styles.code} selectable>
                  {tokenize(line).map((t, j) => (
                    <Text key={j} style={t.kind ? { color: ink[t.kind] } : null}>{t.text}</Text>
                  ))}
                  {line === '' ? ' ' : ''}
                </Text>
              </Animated.View>
            ))}
          </View>
        </ScrollView>
      </ScrollView>

      <View style={styles.actions}>
        <Button style={styles.snackButton} textStyle={styles.shareText} onPress={runInSnack} accessibilityLabel="Run this code as a live app in Expo Snack">Run in Snack</Button>
        <Button variant="secondary" style={styles.shareButton} textStyle={styles.shareOutlineText} onPress={shareEvent} accessibilityLabel="Copy or share this code">Copy or share code</Button>
      </View>
    </Screen>
  );
}

const styles = StyleSheet.create({
  screen: { backgroundColor: ink.background },
  head: { paddingHorizontal: spacing.md, paddingTop: spacing.md },
  slug: { ...typography.slug, color: ink.gutter, marginBottom: spacing.sm },
  vertical: { flex: 1 },
  verticalContent: { paddingBottom: spacing.md },
  horizontalContent: { paddingRight: spacing.lg },
  line: { flexDirection: 'row', minHeight: 20 },
  gutter: {
    ...typography.mono,
    fontSize: 13,
    lineHeight: 20,
    color: ink.gutter,
    textAlign: 'right',
    paddingRight: spacing.sm,
    marginRight: spacing.sm,
    borderRightWidth: 1,
    borderRightColor: ink.rule,
  },
  code: { ...typography.mono, fontSize: 13, lineHeight: 20, color: ink.text },
  snackButton: { backgroundColor: ink.accent },
  shareButton: { borderColor: ink.accent, marginTop: spacing.sm },
  shareText: { color: ink.onAccent },
  shareOutlineText: { color: ink.accent },
  actions: {
    padding: spacing.md,
    borderTopWidth: 1,
    borderTopColor: ink.rule,
    backgroundColor: ink.background,
  },
});
